### ISSUE TITLE
Question: What is the difference between navigel and bui?

### ISSUE THREAD

**Issue by rgrinberg** [DamienCassou/navigel#1]
Hello,

I just saw your presentation recorded at Emacs Conf and first I'd like to say that navigel looks quite nice. Great work!

However, I'm already familiar with a package that seems similar to me: https://github.com/alezost/bui.el Are you familiar with this library? What are the main differences with navigel?

**Comment by DamienCassou** [comment]
Hi @rgrinberg,

I didn't know about bui, thank you very much. This question might interest @alezost (author of [bui](https://github.com/alezost/bui.el)) and @politza (author of [tablist](https://github.com/politza/tablist), a dependency of navigel) as well. From what I can see:

- bui seems really cool and I would probably have used it if I knew about it before. That being said, I would probably have implemented navigel anyway, maybe having bui as a dependency;
- bui seems to be focused on creating 1 list view (e.g., a view listing buffers or a view listing packages) whereas navigel is optimized for creating navigators (e.g., artists ⇒ albums ⇒ songs, or servers ⇒ databases ⇒ documents, or directories ⇒ directories);
- navigel is built with asynchronicity in mind because my use cases all involved asynchronicity (e.g, with music player daemon or couchdb and basecamp API); on the contrary, bui expects `get-entries-function` to return a list of entries and will block Emacs while waiting for that to happen;
- the API of navigel heavily relies on generic methods and overriding whereas bui uses normal functions. This is neither better or worse, just different kind of API ; because I like to use `cl-defstruct` for my domain objects, using generic methods was a perfect fit for me;
- bui has some support for filtering and sorting whereas navigel only has what [tablist](https://github.com/politza/tablist) provides;
- bui has some support for non-list views (i.e., info views);
- navigel has some support for bookmarking and imenu; both could probably be implemented in bui without too much trouble though.

What do you guys think? Is there some convergence we could work on?

**Comment by rgrinberg** [comment]
I quite like the API that you've done with navigel. Having an async API is extremely important to me, so to me that reason alone to choose navigel over bui. My only concern with navigel were all the macros. I'm not a huge fan of macro based API's as they're often quite buggy and hard to learn. But if it's all based on cl-defstruct, then I'm definitely satisfied.

Thanks again for all the great work and sorry for the late reply!

**Comment by DamienCassou** [comment]
> My only concern with navigel were all the macros

There is just one macro in navigel:

```emacs
(defmacro navigel-method (app name args &rest body)
  "Define a method NAME with ARGS and BODY.
This method will only be active if `navigel-app' equals APP."
  (declare (indent 3))
  `(cl-defmethod ,name ,(navigel--insert-context-in-args app args)
     ,@body))
```

As you can see, it's quite lightweight. Or maybe I didn't understand what you meant.

> But if it's all based on cl-defstruct, then I'm definitely satisfied.

There is not a single `cl-defstruct` in navigel even though all the applications I wrote with it heavily use them. Navigel consists of many method descriptions (i.e., `cl-defgeneric`) and a some functions to make use of them.

**Comment by rgrinberg** [comment]
> As you can see, it's quite lightweight. Or maybe I didn't understand what you meant.

Nah, you've understood perfectly. I just had the wrong idea after a very brief glance at the API initially.

> There is not a single cl-defstruct in navigel even though all the applications I wrote with it heavily use them. Navigel consists of many method descriptions (i.e., cl-defgeneric) and a some functions to make use of them.

Yup, sorry that's what I meant. As far as I understand, this is what xref uses for example? I write some elisp from time to tiem, but I admit I don't know it in depth. In any case, your library looks quite good to me and I will prefer it to bui.

All of my original concerns in this issue are now resolved so I will now close this. My only suggestion would be to add your comparison to the README/.

**Comment by DamienCassou** [comment]
> As far as I understand, this is what xref uses for example?

yes. For example:

```emacs
(cl-defgeneric xref-location-marker (location)
  "Return the marker for LOCATION.")
```

> My only suggestion would be to add your comparison to the README/.

feel free to send a PR if you have a few minutes to spare.
